server:
  port: 8081
#  servlet:
#    context-path: /devapi
spring:
  datasource:
    url: jdbc:mysql://localhost:5001/backgroundServer?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
