server:
  port: 8082
#  servlet:
#    context-path: /testapi
spring:
  datasource:
    url: jdbc:mysql://localhost:5002/backgroundServer?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: test
    password: test

